### ISSUE TITLE
Define main color palette.

### ISSUE THREAD

**Issue by eduardodelaguila** [ksquareincmx/krate#2]
Define our base color palette. It should be the project identity.

**Comment by eduardodelaguila** [comment]
I need to see what you have @nailaromero. Please send me the files.

**Comment by nailaromero** [comment]
[COLORPALETTE.pdf](https://github.com/ksquarelabsmx/krate/files/2927539/COLORPALETTE.pdf)

**Comment by mishelashala** [comment]
that's good stuff :)

**Comment by nailaromero** [comment]
[COLORPALETTE.pdf](https://github.com/ksquarelabsmx/krate/files/2953035/COLORPALETTE.pdf)

:)

**Comment by eduardodelaguila** [comment]
> [COLORPALETTE.pdf](https://github.com/ksquarelabsmx/krate/files/2953035/COLORPALETTE.pdf)
> 
> :)

Hi Naila.
The color palette is great, i'll close this issue so we can start using those colors with actual components.
